import mongoose from "mongoose";

const productsSchema = mongoose.Schema(
  {
    DomainId: Number,
    Asin: String,
    ProductId: String,
    TargetPrice: Number,
    Price: Number,
    Rank: Number,
    TotalSellers: Number,
    OutOfStockPercentage: Number,
    OfferFBA: Number,
    OfferFBM: Number,
    SalesEstimatedRevenue: Number,
    EstimatedSales: Number,
    EstimatedRevenue: Number,
    Categories: [Object],
    imagesCSV: String,
    csv: String,
    manufacturer: String,
    title: String,
    lastUpdate: Number,
    lastPriceChange: Number,
    rootCategory: Number,
    productType: Number,
    parentAsin: String,
    variationCSV: String,
    type: String,
    hasReviews: Boolean,
    trackingSince: Number,
    brand: String,
    productGroup: String,
    partNumber: String,
    model: String,
    color: String,
    size: String,
    edition: String,
    format: String,
    packageHeight: Number,
    packageLength: Number,
    packageWidth: Number,
    packageWeight: Number,
    packageQuantity: Number,
    isAdultProduct: Boolean,
    isEligibleForTradeIn: Boolean,
    isEligibleForSuperSaverShipping: Boolean,
    offers: String,
    buyBoxSellerIdHistory: [],
    isRedirectASIN: Boolean,
    isSNS: Boolean,
    author: String,
    binding: String,
    numberOfItems: Number,
    numberOfPages: Number,
    publicationDate: Number,
    releaseDate: Number,
    languages: [],
    lastRatingUpdate: Number,
    ebayListingIds: [],
    lastEbayUpdate: Number,
    eanList: [],
    upcList: [],
    liveOffersOrder: [],
    frequentlyBoughtTogether: [],
    features: [],
    description: String,
    promotions: [],
    newPriceIsMAP: Boolean,
    coupon: [],
    availabilityAmazon: Number,
    listedSince: Number,
    fbaFees: Object,
    variations: [],
    itemHeight: Number,
    itemLength: Number,
    itemWidth: Number,
    itemWeight: Number,
    salesRankReferenceHistory: Number,
    launchpad: Boolean,
    isB2B: Boolean,
    stats: Object,
    offersSuccessful: Boolean,
    g: Number,
    categoryTree: [
      {
        catId: Number,
        name: String,
      },
    ],
    SellerRank: Number,
    ProductStatus: Number,
    IsCopied: Boolean,
    ColorCode: Number,
  },
  { timestamps: true }
);
export const Products = mongoose.model("Products", productsSchema);
